### ISSUE TITLE
Option to disable when offscreen

### ISSUE THREAD

**Issue by lajoiemedia** [yongjun21/st-scrolly#7]
It would be helpful to have an option to disable the render functions when the scrolly is offscreen (say, using an intersectionobserver).

I have a project which uses multiple st-scrollies on the same page and don't want all their renderBackground etc. functions firing on every scroll increment.

**Comment by yongjun21** [comment]
The reason IntersectionObserver was not used in the original design for this component is because the majority of the use case at Straits Times requires pixel level tracking. To achieve that with IntersectionObserver will require setting a large number of `threshold`s (one for each pixel). That's why we relied on the simpler and more traditionally way which is to track scroll event and `element.getBoundingClientRect()` even though it's less optimal than IntersectionObserver.

I did included an optimization that is not listening directing on scroll event but throttling to events to match browser frame rate: https://github.com/yongjun21/st-scrolly/blob/master/packages/%40st-graphics/react-scrolly/src/index.jsx#L220.

For further optimization like the one you requested. My suggestion is you can copy the JSX and CSS into your project and directly modify the code. What you need is create a wrapper for the `handleResize` function (https://github.com/yongjun21/st-scrolly/blob/master/packages/%40st-graphics/react-scrolly/src/index.jsx#L80) that wraps over both the original handler and the `frameRateLimited` wrapper. Here is a sample:

```javascript
// say you have a global variable tracking the offscreen state

let offscreen = true

function disableWhenOffscreen (handler, context = null) {
  return (...args) => {
    if (offscreen) return
    return handler.apply(context, args)
  }
}
```

**Comment by lajoiemedia** [comment]
Sorry I was a little late responding, I was on deadline. Love this project, btw, it's been very useful.

I think what I really would like is a way to know which is the active scroller when I have multiple on a page. That way I can skip expensive and pointless renders with my renderBackground/renderForeground handlers.

 I know that you are already detecting which is the active scrolly because the class of the scrolly div goes from `st-scrolly` to `st-scrolly active` when the scrolly comes on screen. It would be great if that info was passed to the renderBackground/renderForeground handler as a parameter. That way I could decide whether to abort the render or not based on that information.
 
(Note that I don't need a workaround -- I've already implemented one in my code and it's working fine. But it would be a great feature to have for future projects.)

**Comment by lajoiemedia** [comment]
I made a pull request with a possible implementation
